### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by MrHash** [gnosis/gnosis-dev-kit#2]
Running `docker-compose build` on MacOS El Capitan Docker v17.07.0-ce i get 
`ERROR: Service 'gnosisdb_web' failed to build: The command '/bin/sh -c pip install -qr /tmp/requirements.txt' returned a non-zero code: 1`

**Comment by giacomolicari** [comment]
Hi @MrHash could you give us more details about:
- OS System (Linux, Windows, OSX)
- Docker version
- Docker Compose version

**Comment by MrHash** [comment]
yup
````
MacOS 10.11.6 El Captian
Docker v17.07.0-ce-rc4
Docker Compose v1.16.0-rc1
```

**Comment by denisgranha** [comment]
Hello @MrHash 
Try:
```
docker-compose down --rmi
sudo docker-compose build --no-chache
```

**Comment by MrHash** [comment]
Sorry i'm afraid i'm not comfortable running docker with sudo.. i've never needed to do that before

**Comment by denisgranha** [comment]
the error you shared at the beginning is related with the python installation of gnosisdb, from this file https://github.com/gnosis/gnosisdb/blob/master/requirements.txt

I think it can be either:
1. Network issues, you cannot download the dependencies due to a firewall
2. Disk limitations. Maybe related with the docker configurations and the amount of free disk space.

**Comment by MrHash** [comment]
Ok I don't think i have any firewall issues, so i'll upgrade versions and reboot etc. in the meantime.

**Comment by giacomolicari** [comment]
@MrHash check this: https://docs.docker.com/engine/installation/linux/linux-postinstall/
